name: Build CI

on:
  push:
    branches: [main]
    paths: ['src/**', 'public/**']

permissions: write-all

#  並列実行阻止
concurrency:
  group: ${{ github.workflow }}

env:
  DOCKER_REPOSITORY: haruapp
  DOCKER_IMAGE_NAME: myenglish-front
  RELEASE_BRANCH: main

jobs:
  build:
    # マージされたときのみ実行
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # DockerHubにログイン : https://github.com/docker/login-action
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 'Build Docker image'
        run: docker build --platform linux/amd64 -t ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:latest ./
      - name: 'Push Docker Image'
        run: docker push ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:latest

